[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "atalaya"
version = "1.0.0"
description = "Generador de contraseñas y passphrases criptográficamente seguro, con GUI de consola industrial y CLI."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
authors = [{ name = "vabeba94" }]
dependencies = [
    "click>=8.1",
    "PySide6>=6.6",
    "pyperclip>=1.8",
    "cryptography>=42.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.4"]

[project.scripts]
atalaya = "atalaya.cli.main:main"
atalaya-gui = "atalaya.gui.app:run"
atalaya-history = "atalaya.cli.history:history_cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"atalaya.data" = ["*.txt"]
"atalaya.gui" = ["*.qss"]
"atalaya.gui.assets" = ["*.ttf"]
